apiVersion: v1
kind: ConfigMap
metadata:
  name: hsd-oauth-proxy-env-cm
data:

  OAUTH2_PROXY_COOKIE_EXPIRE: {{ .Values.envVariables.OAUTH2_PROXY_COOKIE_EXPIRE | quote }}
  OAUTH2_PROXY_COOKIE_REFRESH: {{ .Values.envVariables.OAUTH2_PROXY_COOKIE_REFRESH | quote }}
  OAUTH2_PROXY_HTTP_ADDRESS: {{ .Values.envVariables.OAUTH2_PROXY_HTTP_ADDRESS | quote }}
  OAUTH2_PROXY_METRICS_ADDRESS: {{ .Values.envVariables.OAUTH2_PROXY_METRICS_ADDRESS | quote }}
  OAUTH2_PROXY_PROXY_PREFIX: {{ .Values.envVariables.OAUTH2_PROXY_PROXY_PREFIX | quote }}
  OAUTH2_PROXY_REDIRECT_URL: {{ .Values.envVariables.OAUTH2_PROXY_REDIRECT_URL | quote }}
  OAUTH2_PROXY_STANDARD_LOGGING: {{ .Values.envVariables.OAUTH2_PROXY_STANDARD_LOGGING | quote }}
  OAUTH2_PROXY_REQUEST_LOGGING: {{ .Values.envVariables.OAUTH2_PROXY_REQUEST_LOGGING | quote }}
  OAUTH2_PROXY_AUTH_LOGGING:  {{ .Values.envVariables.OAUTH2_PROXY_AUTH_LOGGING | quote }}

  OAUTH2_PROXY_COOKIE_SECURE: "true"
  OAUTH2_PROXY_EMAIL_DOMAINS: "*"
  OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
  OAUTH2_PROXY_INSECURE_OIDC_SKIP_ISSUER_VERIFICATION: "true"
  OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
  OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
  OAUTH2_PROXY_PASS_BASIC_AUTH: "true"
  OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
  OAUTH2_PROXY_SET_INTROSPECTION_VALUE: "true"
  OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
  OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: "true"
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
  OAUTH2_PROXY_PROVIDER: "oidc"
  OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: "oidc"
  OAUTH2_PROXY_SESSION_STORE_TYPE: "redis"
  OAUTH2_PROXY_UPSTREAMS: "static://"  
  OAUTH2_PROXY_STANDARD_LOGGING_FORMAT: "info|CustomLogEvent||OAuth2Proxy|[{{.Timestamp}}] [{{.File}}] {{.Message}}"
  OAUTH2_PROXY_REQUEST_LOGGING_FORMAT: "info|CustomLogEvent||OAuth2Proxy|{{.Client}} - [{{.Timestamp}}] {{.Host}} {{.RequestMethod}} {{.Upstream}} {{.RequestURI}} {{.Protocol}} {{.UserAgent}} {{.StatusCode}} {{.ResponseSize}} {{.RequestDuration}}"
  OAUTH2_PROXY_AUTH_LOGGING_FORMAT: "info|CustomLogEvent||OAuth2Proxy|{{.Client}} - [{{.Timestamp}}] [{{.Status}}] {{.Message}}"